### ISSUE TITLE
Incomplete support for standard fonts

### ISSUE THREAD

**Issue by bh4017** [rkone/sharpzebra#12]
The sharpzebra API provides for the following Standard Fonts:

- Smallest
- Small
- Normal
- Large
- Largest

It is not clear to me which of the standard fonts this maps to via ZPL.  The standard fonts provided via ZPL are:

A, B, D, E, F, G, H, GS, P, Q, R, S, T, U, V and 0.

0 Is a scalable font, which does not appear to be provided for via the sharpzebra API.

**Comment by bh4017** [comment]
As a result of this issue I found it preferable to write my own software for sending raw ZPL to the printer over USB.  This way I am in complete control of the commands and I can use the built in scalable font (^A0N).  It's working fine.

But thanks for writing your Zebra wrapper software - this got me started and showed me what can be done.  The issue I raised here still stands as a potential improvement for your software.

**Comment by rkone** [comment]
The Standard Fonts are EPL fonts, which are available to ZPL also.

Regarding ^A, it's been too long, I don't recall why it isn't included in the library.  Zebra's documentation has changed, maybe the previous ZPL guides didn't specify which ZPL Standard Fonts are "usually" included? It's also possible it was simply never implemented as no one using the library needed the feature.  I've always used ^A@ myself. 

Not implementing ^A certainly seems like a strange oversight now, especially since they look much nicer than the EPL Standard Fonts.

Thanks for the tip.  I'll look into it when I get the chance.  I'm glad the library proved useful for you even if just as a guide!

**Comment by rkone** [comment]
The problem was that the library was trying to reuse Font names across ZPL and EPL, which really doesn't work out. I've updated the enums with the latest version to make 2 separate lists. Thanks again for the heads up on this.
