### ISSUE TITLE
text to graphic support

### ISSUE THREAD

**Issue by viktoraskas** [rkone/sharpzebra#19]
Hi,

can you add text to graphic conversion support?
I try print text in my local language, but printer just ignores that chars - ąčęėįšųūžĄČĘĖĮŠŲŪŽ.
It would be great to have function converts text to graphic field.

Thank You

**Comment by rkone** [comment]
I had something [like that for EPL](https://github.com/rkone/sharpzebra/blob/master/Com.SharpZebra/Commands/CustomFontEPLCommand.cs), but it would never be a great solution.
The proper way to handle it depends a little on the printer you have.  I do have the option to choose a different codepage other than the default 850, that may work for you.  
To use that, you'd do something like this:
`res.AddRange(ZPLCommands.TextWrite(10, 150, ElementDrawRotation.NO_ROTATION, ZPLFont.STANDARD_BOLD2, 15, 10, "ąčęėįšųūžĄČĘĖĮŠŲŪŽ", (int)Codepage8KDU.Germany));`

Finally, StackOverflow had an answer [here](https://stackoverflow.com/questions/4669965/how-to-print-with-win-1250-codepage-on-zebra-printer) that said Encoding.UTF8 was a simple solution.  This would require a change to the library, maybe more method overrides.  I'm a little hesitant to do that since it's already a bit insane with overrides already, but let me know what your testing finds out!

**Comment by rkone** [comment]
Actually, your request is already in ZPL also, I just forgot. Check out [ZPLCommands.CustomStringWrite](https://github.com/rkone/sharpzebra/blob/master/Com.SharpZebra/Commands/GraphicZPLCommand.cs)
