### ISSUE TITLE
Info ..

### ISSUE THREAD

**Issue by sandorkacso** [rkone/sharpzebra#8]
Dear rkone,
Where I can find a test project for this project?

SK

**Comment by rkone** [comment]
It doesn't exist. What would you be looking for in a test project?

**Comment by caseypharr** [comment]
I am seeing same issue. I think the test project question is because the project does not load, satting it is missing imports and cannot find path for TestProject.  So i updated the Project file to remove it from the .sln file. Still get this from fresh download though, and try to open in VS 2017.

"..\Downloads\sharpzebra-master\sharpzebra-master\Com.SharpZebra\Com.SharpZebra.csproj : error  : Project file is incomplete. Expected imports are missing."

**Comment by rkone** [comment]
Thanks, I've updated the repo so the references to that project have been removed.
